### ISSUE TITLE
Does not fully work in a relevant browser! Update your ext, please.

### ISSUE THREAD

**Issue by led9** [darktrojan/betterimageviewer#18]
Hello,
Firefox Nightly 64 bit:
Scrolbars do not work - they are visible, but they do not react to the mouse. It is impossible to move the image by them.

huge image, if you make it size more than the browser window size - it is not possible to move in any way. Not moving to the right, nor left or upwards. Changing the scale with the mouse or buttons is working normally.

Example -  a huge image, clicking the button of your extension "scale horizontal", the extension does it.
I want to move the image up or down - and this does not work. nothing works.

**Comment by irvinm** [comment]
@darktrojan, I tried with @wenereth-arkhilmor's pull request and it worked really well to not only handle moving of an image (document.body -> window), but to also restore the centering of an image smaller than the viewport to be centered horizontally and vertically via CSS rather than the new default behavior of centering horizontally, but leaving the image at the top of the page.

Would you consider reviewing and merging his PR to a new version of the addon?

**Comment by Wassss** [comment]
@darktrojan  Any update on this?
update:
New version that i make based on @wenereth-arkhilmor [Pull request](https://github.com/darktrojan/betterimageviewer/pull/20)
https://github.com/Wassss/betterimageviewer/releases

**Comment by darktrojan** [comment]
> @darktrojan Any update on this?

Yes, here's an update. I have a very busy job and don't have time to respond to things immediately. There really is no need to comment in multiple issues about the same thing.
